from fpdf import FPDF
import csv
from datetime import datetime

#  STEP 1: Custom PDF Class
class PDFReport(FPDF):
    def header(self):
        self.set_fill_color(70, 130, 180)  # Steel Blue
        self.set_text_color(255)
        self.set_font("Arial", "B", 16)
        self.cell(0, 15, "  Sales Report", ln=True, align='C', fill=True)
        self.set_font("Arial", "", 11)
        self.set_text_color(0)
        self.cell(0, 10, "Generated by Automated Report System", ln=True, align='C')
        self.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 10)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()}", align='C')

    def add_table(self, data):
        col_widths = [50, 40, 40, 40]
        headers = ["Product", "Price ", "Quantity", "Total "]

        self.set_fill_color(100, 149, 237)
        self.set_text_color(255)
        self.set_font("Arial", "B", 12)
        for i in range(4):
            self.cell(col_widths[i], 10, headers[i], border=1, align='C', fill=True)
        self.ln()

        self.set_font("Arial", "", 12)
        self.set_text_color(0)
        fill = False
        for row in data:
            for i,iteam in enumerate(row):
                iteam=str(iteam).encode('latin-1',errors='ignore').decode('latin-1')
            # self.set_fill_color(240, 248, 255)
            # for i in range(4):
                self.cell(col_widths[i], 10, str(row[i]), border=1, align='C', fill=fill)
            self.ln()
            fill = not fill

    def add_summary(self, data):
        total = sum([row[3] for row in data])
        self.ln(5)
        self.set_font("Arial", "B", 14)
        self.set_fill_color(255, 215, 0)  # Gold
        self.set_text_color(0)
        self.cell(0, 12, f"TOTAL SALES: {total:.2f}", ln=True, align='R', fill=True)

# STEP 2: read_csv function — must be outside class
def read_csv(filename):
    data = []
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            product = row[0]
            price = float(row[1])
            quantity = int(row[2])
            total = price * quantity
            data.append([product, price, quantity, total])
    return data

#  STEP 3: Main Program
pdf = PDFReport()
pdf.add_page()
sales_data = read_csv("product_data.csv")  #  Make sure this file exists
pdf.add_table(sales_data)
pdf.add_summary(sales_data)
pdf.output("file3.pdf")
print(" Stylish PDF generated successfully: file3.pdf")